name: Terraform Format Check

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  terraform-fmt:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.0

      - name: Terraform Format
        run: terraform fmt -check -recursive
